layout_spectrum: 0.44441944074936873
typography_spectrum: 0.919397297620423
color:
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  brandStrength: 0.676463430879527
  lightness: 0.24005541704963929
  saturation: 0.6941852361144553
  rhythmicContrast: 0.36844998609293067
analytics:
  google: UA-98687120-1
author:
  name: Jochem Herber
  email: Jochemherber@gmail.com
name: Only amazing
url: 'https://only-amazing.com'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Amazing Technology
    url: 'http://amazingtech.only-amazing.com/'
    type: external
  - name: Amazing Science
    url: 'http://amazingscience.only-amazing.com/'
    type: external
  - name: Amazing People
    url: 'http://amazingpeople.only-amazing.com/'
    type: external
  - name: Amazing Experiences
    url: 'http://amazingexperience.only-amazing.com/'
    type: external
  - name: Amazing World
    url: 'http://amazingworld.only-amazing.com/'
    type: external
  - name: Contact us
    id: 2bc3d7c1-7ac1-41bb-89b3-44a016681ff8
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4d1ddbae-14e1-4fe5-a758-dbc92b68745d.jpg
title: 'This is where you will find #YourAmazing'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F58381735&url=https%3A%2F%2Fvimeo.com%2F58381735&image=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F405137448_640.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=vimeo"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Success Together
          url: 'https://vimeo.com/user3665343'
          avatar: {}
      related: []
      publisher:
        url: 'https://vimeo.com/'
        name: Vimeo
        favicon: 'https://f.vimeocdn.com/images_v6/favicon.ico'
        domain: vimeo.com
      keywords: []
      description: >-
        Repost from Hadouken on YouTube: Here are some of the videos we used
        (and a few great ones that didn't make it). Check out the originals and
        support their channels!
      '@type': VideoObject
      app_links:
        - url: 'vimeo://app.vimeo.com/videos/58381735'
          type: ios
          namespace: ai
          app_name: Vimeo
          app_store_id: '425194759'
        - should_fallback: 'true'
          app_name: Vimeo
          package: com.vimeo.android.videoapp
          url: 'vimeo://app.vimeo.com/videos/58381735'
          namespace: ai
          type: web
        - url: 'vimeo://app.vimeo.com/videos/58381735'
          namespace: twitter
          type: ipad
          name: Vimeo
          id: '425194759'
        - url: 'vimeo://app.vimeo.com/videos/58381735'
          namespace: twitter
          type: iphone
          name: Vimeo
          id: '425194759'
        - url: 'vimeo://app.vimeo.com/videos/58381735'
          namespace: twitter
          type: googleplay
          name: Vimeo
          id: com.vimeo.android.videoapp
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://vimeo.com/58381735'
      title: PEOPLE ARE AWESOME 2013
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  We give you the most amazing content on the web, choose your passion and
  enjoy!
github: true
purpose: []
